/home/ubuntu/my_project/run_server.sh: 3: source: not found
/home/ubuntu/my_project/run_server.sh: 14: source: not found
/home/ubuntu/my_project/run_server.sh: 15: source: not found
/home/ubuntu/my_project/run_server.sh: 16: python: not found
Traceback (most recent call last):
  File "manage.py", line 12, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 14, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
